Task 1 completed
VladyslavBublii/AltexSoftCurses pull request #1
Opened 2021-04-12 21:51 UTC by VladyslavBublii

Task 1 completed

2021-04-13 18:10 UTC, serhii-shkodenko requested changes
Есть существенные замечания по логике. Поправь, пожалуйста.

2021-04-13 18:10 UTC, serhii-shkodenko commented on Task1/Lecture1/HomeWork.cs
> +            //decimal fullPrice = default;
Закомментированный код лучше удалять из пулл реквеста. Его не должно быть на продакшене.

2021-04-13 18:10 UTC, serhii-shkodenko commented on Task1/Lecture1/HomeWork.cs
> +            if (street.Split(' ')[1] == nextStreet.Split(' ')[1])
Здесь сравнивается только первое слово в названии улицы. Улицы "North Heather Street" и "North Heather Avenue" это разные улицы. Это надо поправить.

2021-04-13 18:10 UTC, serhii-shkodenko commented on Task1/Lecture1/HomeWork.cs
> +            decimal[] deliveryPrices = new decimal[destinations.Count()];
Используй неявное определение типа с помощью `var`. В чате есть объяснение почему.

2021-04-13 18:10 UTC, serhii-shkodenko commented on Task1/Lecture1/HomeWork.cs
> +            try
Блок try.. catch следуте размещать в вызывающем коде. Мы еще не проходили исключения, поэтому можно просто удалить.

2021-04-13 18:10 UTC, serhii-shkodenko commented on Task1/Lecture1/HomeWork.cs
> +                return price*(decimal) 0.84;
Если переводить цену из евро в доллары, то долларов будет больше. Условно 100 евро это 120 долларов. Здесь нужно разделить.

2021-04-13 18:17 UTC, VladyslavBublii commented on Task1/Lecture1/HomeWork.cs
> +                return price*(decimal) 0.84;
120(USD)*0.84 = 100,8

можно оставить ?

2021-04-13 18:21 UTC, serhii-shkodenko commented on Task1/Lecture1/HomeWork.cs
> +                return price*(decimal) 0.84;
Достаточно просто вместо знака умножения написать знак деления.

2021-04-13 18:37 UTC, VladyslavBublii commented on Task1/Lecture1/HomeWork.cs
> +            //decimal fullPrice = default;
Я так понимаю, для этого надо будет удалить коммит ?

2021-04-13 18:51 UTC, serhii-shkodenko commented on Task1/Lecture1/HomeWork.cs
> +            //decimal fullPrice = default;
Нет, наоборот, добавить новый. Сделай необходимые изменения локально, закомить их тоже локально. Отправ на ремоут. Изменения появятся здесь. Только сделать это нужно в ветке, из которой ты делаешь пулл реквест в ветку `main`.

2021-04-13 21:38 UTC, serhii-shkodenko requested changes

2021-04-13 21:38 UTC, serhii-shkodenko commented on Task1/Lecture1/HomeWork.cs
> +            var concatAdress = String.Join(" ", allWords, 1, 2);
Ты пытаешься выделить одну улицу из адреса, но не учел, что ее название может состоять более чем из двух слов.

2021-04-13 21:38 UTC, serhii-shkodenko commented on Task1/Lecture1/HomeWork.cs
> +            var destinationsBuf = destinations.Concat(new string[] { null }).ToArray();
Здесь ты добавил путой элемент коллекции, чтобы не выходить за пределы по n+1. Это очень сомнительное решение. Попробуй найти другое.

2021-04-13 21:51 UTC, VladyslavBublii commented on Task1/Lecture1/HomeWork.cs
> +            var concatAdress = String.Join(" ", allWords, 1, 2);
Можно для проверки юзать индекс в конце адреса - FL 32927 ?

2021-04-14 11:11 UTC, VladyslavBublii commented on Task1/Lecture1/HomeWork.cs
> +            var destinationsBuf = destinations.Concat(new string[] { null }).ToArray();
Какого-то удачного решения без переписывания почти всей программы(массив destinations используется в главном цикле) я к сожалению не нашёл.

2021-04-15 16:01 UTC, serhii-shkodenko approved these changes
Код выполняет свою работу. Можно мержить.

2021-04-15 16:14 UTC, merged